sudo: required

services:
  - docker
language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
# keep the npm cache to speed up installs
cache:
  directories:
    - '$HOME/.npm'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - npm install
  - npm install -g npx

script:
  - yarn build
  - yarn doc
  - yarn test:unit
  - yarn lint
  - yarn audit
  - yarn test:integration
