sudo: required

services:
  - docker
language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
# keep the npm cache to speed up installs
cache:
  directories:
    - '$HOME/.npm'

install:
  - npm install
  - npm install -g npx
  - npx snyk auth $SNYK_TOKEN

script:
  - yarn build
  - yarn doc
  - yarn test:unit
  - yarn lint
  - npx snyk test
  - yarn test:integration
